[package]
name = "leetdraw-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
rocket = { version = "0.5.1", features = ["json"]}
rusqlite = "0.33.0"
rust-argon2 = "2.1.0"
serde = { version = "1.0", features = ["derive"]}
tokio = { version = "1", features = ["full"] }
